[package]
name = "tentaclers-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.20"
regex = "1.9.3"
serde_json = "1.0.105"
tracing = "0.1.37"
